name: Periodic Workflow

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:    # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install ffmpeg in the virtual environment
      run: |
        source venv/bin/activate
        python -m pip install --upgrade pip
        sudo apt-get update
        sudo apt-get install ffmpeg -y

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install yt-dlp

    - name: Run main.py with Timeout
      run: |
        # Run main.py and wait for at most 238 minutes
        timeout 225m python bot.py
